modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
displayURL="https://example.com/"
description="This is an Example Mod"
